### ISSUE TITLE
Provide demo

### ISSUE THREAD

**Issue by SyntaxRules** [ShoppinPal/ng-mobile-menu#11]
Is there a demo on the web for this? The documentation says I can look in the demo folder in the repo- but I'd rather not download the repo and all its dependencies to see it.

**Comment by SyntaxRules** [comment]
Found it here: http://shoppinpal.github.io/ng-mobile-menu/demo/#/skinny. Perhaps adding this to the Readme.md would be good.

**Comment by pulkitsinghal** [comment]
@SyntaxRules - the original author of this code is now using https://github.com/dpiccone/ng-pageslide and this is no longer under development, please consider switching.
